/**
 * UC6.2 - Mock seed data.
 *
 * Dataset ban dau de receptionist co du yeu cau o cac trang thai khac nhau
 * minh hoa toan bo workflow: cho_xu_ly / dang_xu_ly / de_xuat_lich_khac /
 * da_tao_lich_hen / da_tu_choi / da_huy. Khi backend Laravel san sang co
 * the di chuyen sang server-side seed.
 */

import {
  EMAIL_STATUS,
  REQUEST_STATUS,
  APPOINTMENT_STATUS,
} from './constants';
import {
  buildHistoryEntry,
  generateAppointmentCode,
  generatePatientCode,
  generateRequestCode,
} from './utils';

// Tao ISO datetime tuong doi tu hien tai (de mock data luon "tuoi").
const isoOffset = (deltaHours = 0) => {
  const d = new Date();
  d.setHours(d.getHours() + deltaHours);
  return d.toISOString();
};

const isoDate = (deltaDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + deltaDays);
  return d.toISOString().slice(0, 10);
};

// Patients seed (DR12).
export const PATIENT_PROFILES = [
  {
    id: 1,
    code: generatePatientCode(1234),
    name: 'Nguyen Van An',
    gender: 'male',
    birthdate: '1990-05-12',
    age: 35,
    address: '123 Nguyen Trai, P. Ben Thanh, Quan 1',
    phone: '0901234567',
    email: 'an.nguyenvan@gmail.com',
    active: true,
    last_visit_at: '2025-03-10',
    matched_via: ['phone'],
  },
  {
    id: 2,
    code: generatePatientCode(9876),
    name: 'Nguyen Van An',
    gender: 'male',
    birthdate: '1989-01-05',
    age: 36,
    address: '45 Le Loi, P. Ben Nghe, Quan 1',
    phone: '0901234567',
    email: null,
    active: false,
    last_visit_at: null,
    matched_via: ['phone'],
  },
  {
    id: 3,
    code: generatePatientCode(5566),
    name: 'Tran Thi Binh',
    gender: 'female',
    birthdate: '1995-08-20',
    age: 30,
    address: '78 Hai Ba Trung, P. Tan Dinh, Quan 1',
    phone: '0912345678',
    email: 'binh.tranthi@gmail.com',
    active: true,
    last_visit_at: '2024-12-01',
    matched_via: ['phone', 'email'],
  },
  {
    id: 4,
    code: generatePatientCode(7788),
    name: 'Le Minh Cuong',
    gender: 'male',
    birthdate: '1985-03-15',
    age: 40,
    address: '90 Nam Ky Khoi Nghia, P. Vo Thi Sau, Quan 3',
    phone: '0934567890',
    email: 'cuong.leminh@gmail.com',
    active: true,
    last_visit_at: '2025-02-15',
    matched_via: ['phone'],
  },
];

// Online booking requests seed.
// 5 pending, 2 processing, 1 propose_other, 3 appointment_created,
// 1 rejected, 1 canceled - tong 13 yeu cau.
export const ONLINE_BOOKING_REQUESTS = [
  {
    id: 1,
    code: generateRequestCode(123),
    status: REQUEST_STATUS.PENDING,
    name: 'Nguyen Van An',
    phone: '0901234567',
    email: 'an.nguyenvan@gmail.com',
    service_ids: ['braces'],
    branch_id: 'q1',
    preferred_date: isoDate(1),
    preferred_time_slot_id: '09-10',
    customer_note: 'Muon duoc tu van chi tiet ve nieng rang mac cai kim loai.',
    internal_note: '',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: null,
    processed_at: null,
    source: 'landing_page',
    submitted_at: isoOffset(-22),
    device: 'Windows · Chrome',
    ip: '113.160.245.113',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-22), actor: 'He thong', note: 'Yeu cau duoc gui tu landing page' }),
      buildHistoryEntry('request_received', { at: isoOffset(-22), actor: 'He thong', note: 'Yeu cau duoc he thong tiep nhan thanh cong' }),
    ],
  },
  {
    id: 2,
    code: generateRequestCode(122),
    status: REQUEST_STATUS.PENDING,
    name: 'Tran Thi Binh',
    phone: '0912345678',
    email: 'binh.tranthi@gmail.com',
    service_ids: ['scaling'],
    branch_id: 'q1',
    preferred_date: isoDate(0),
    preferred_time_slot_id: '14-15',
    customer_note: 'Mong duoc dat lich vao cuoi tuan.',
    internal_note: '',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: null,
    processed_at: null,
    source: 'landing_page',
    submitted_at: isoOffset(-26),
    device: 'iPhone · Safari',
    ip: '14.169.20.10',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-26), actor: 'He thong' }),
      buildHistoryEntry('request_received', { at: isoOffset(-26), actor: 'He thong' }),
    ],
  },
  {
    id: 3,
    code: generateRequestCode(121),
    status: REQUEST_STATUS.PROPOSE_OTHER,
    name: 'Le Minh Cuong',
    phone: '0934567890',
    email: 'cuong.leminh@gmail.com',
    service_ids: ['implant'],
    branch_id: 'q3',
    preferred_date: isoDate(3),
    preferred_time_slot_id: '08-09',
    customer_note: 'Da tham kham va can tu van chi phi implant.',
    internal_note: 'Khach VIP - uu tien sap xep.',
    patient_id: 4,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.SENT,
    processed_by: 'le_tan',
    processed_at: isoOffset(-12),
    source: 'landing_page',
    submitted_at: isoOffset(-48),
    device: 'macOS · Safari',
    ip: '171.244.10.25',
    proposed_slots: [
      { date: isoDate(4), time_slot_id: '09-10' },
      { date: isoDate(5), time_slot_id: '10-11' },
    ],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-48), actor: 'He thong' }),
      buildHistoryEntry('processing_started', { at: isoOffset(-13), actor: 'le_tan' }),
      buildHistoryEntry('patient_linked', { at: isoOffset(-12), actor: 'le_tan', note: 'Lien ket voi BN20257788 - Le Minh Cuong' }),
      buildHistoryEntry('alternative_proposed', { at: isoOffset(-12), actor: 'le_tan', note: 'Khung gio mong muon khong con slot, da de xuat 2 lich thay the.' }),
      buildHistoryEntry('email_sent', { at: isoOffset(-12), actor: 'He thong', note: 'Email de xuat lich khac da gui den cuong.leminh@gmail.com' }),
    ],
  },
  {
    id: 4,
    code: generateRequestCode(120),
    status: REQUEST_STATUS.APPOINTMENT_CREATED,
    name: 'Pham Hoang Duy',
    phone: '0945678901',
    email: 'duy.pham@gmail.com',
    service_ids: ['whitening'],
    branch_id: 'q1',
    preferred_date: isoDate(-1),
    preferred_time_slot_id: '15-16',
    customer_note: 'Can tay trang truoc le cuoi.',
    internal_note: 'Da xac nhan qua dien thoai.',
    patient_id: 1,
    appointment_id: 1,
    appointment_code: generateAppointmentCode(1),
    appointment_status: APPOINTMENT_STATUS.WAITING_DOCTOR_ASSIGNMENT,
    email_status: EMAIL_STATUS.SENT,
    processed_by: 'le_tan',
    processed_at: isoOffset(-72),
    source: 'landing_page',
    submitted_at: isoOffset(-90),
    device: 'Windows · Chrome',
    ip: '113.160.5.5',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-90), actor: 'He thong' }),
      buildHistoryEntry('processing_started', { at: isoOffset(-73), actor: 'le_tan' }),
      buildHistoryEntry('patient_linked', { at: isoOffset(-72), actor: 'le_tan', note: 'Lien ket voi BN20251234' }),
      buildHistoryEntry('appointment_created', { at: isoOffset(-72), actor: 'le_tan', note: 'Tao lich hen ' + generateAppointmentCode(1) }),
      buildHistoryEntry('email_sent', { at: isoOffset(-72), actor: 'He thong', note: 'Email xac nhan da gui den duy.pham@gmail.com' }),
    ],
  },
  {
    id: 5,
    code: generateRequestCode(119),
    status: REQUEST_STATUS.REJECTED,
    name: 'Vo Thi Em',
    phone: '0956789012',
    email: 'em.vo@gmail.com',
    service_ids: ['orthognathic'],
    branch_id: 'q1',
    preferred_date: isoDate(7),
    preferred_time_slot_id: '10-11',
    customer_note: 'Mong duoc phau thuat chinh hinh ham.',
    internal_note: 'Dich vu nay tam ngung tiep nhan.',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.SENT,
    processed_by: 'le_tan',
    processed_at: isoOffset(-100),
    source: 'landing_page',
    submitted_at: isoOffset(-120),
    device: 'Android · Chrome Mobile',
    ip: '113.161.50.5',
    proposed_slots: [],
    reject_reason: 'Khong dung pham vi dich vu phong kham',
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-120), actor: 'He thong' }),
      buildHistoryEntry('processing_started', { at: isoOffset(-101), actor: 'le_tan' }),
      buildHistoryEntry('request_rejected', { at: isoOffset(-100), actor: 'le_tan', note: 'Khong dung pham vi dich vu phong kham' }),
      buildHistoryEntry('email_sent', { at: isoOffset(-100), actor: 'He thong' }),
    ],
  },
  {
    id: 6,
    code: generateRequestCode(118),
    status: REQUEST_STATUS.PENDING,
    name: 'Hoang Thi Phuong',
    phone: '0967890123',
    email: 'phuong.hoang@gmail.com',
    service_ids: ['endodontic'],
    branch_id: 'q3',
    preferred_date: isoDate(2),
    preferred_time_slot_id: '16-17',
    customer_note: 'Dau buot rang lien tuc.',
    internal_note: '',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: null,
    processed_at: null,
    source: 'landing_page',
    submitted_at: isoOffset(-30),
    device: 'iPhone · Safari',
    ip: '113.160.30.30',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-30), actor: 'He thong' }),
    ],
  },
  {
    id: 7,
    code: generateRequestCode(117),
    status: REQUEST_STATUS.PROCESSING,
    name: 'Bui Anh Khoa',
    phone: '0978901234',
    email: 'khoa.bui@gmail.com',
    service_ids: ['braces'],
    branch_id: 'q7',
    preferred_date: isoDate(3),
    preferred_time_slot_id: '10-11',
    customer_note: 'Quan tam toi mac cai trong suot.',
    internal_note: 'Khach yeu cau lien lac sau 19h.',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: 'le_tan',
    processed_at: isoOffset(-1),
    source: 'landing_page',
    submitted_at: isoOffset(-36),
    device: 'macOS · Safari',
    ip: '171.244.20.20',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-36), actor: 'He thong' }),
      buildHistoryEntry('processing_started', { at: isoOffset(-1), actor: 'le_tan' }),
    ],
  },
  {
    id: 8,
    code: generateRequestCode(116),
    status: REQUEST_STATUS.CANCELED,
    name: 'Do Thi Lan',
    phone: '0989012345',
    email: 'lan.do@gmail.com',
    service_ids: ['porcelain'],
    branch_id: 'q1',
    preferred_date: isoDate(-3),
    preferred_time_slot_id: '11-12',
    customer_note: 'Da chuyen sang phong kham khac.',
    internal_note: 'Khach huy do thay doi ke hoach.',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.SENT,
    processed_by: 'le_tan',
    processed_at: isoOffset(-50),
    source: 'landing_page',
    submitted_at: isoOffset(-150),
    device: 'Windows · Chrome',
    ip: '113.160.10.10',
    proposed_slots: [
      { date: isoDate(-2), time_slot_id: '14-15' },
    ],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-150), actor: 'He thong' }),
      buildHistoryEntry('alternative_proposed', { at: isoOffset(-130), actor: 'le_tan' }),
      buildHistoryEntry('request_canceled', { at: isoOffset(-50), actor: 'le_tan', note: 'Khach huy do thay doi ke hoach' }),
      buildHistoryEntry('email_sent', { at: isoOffset(-50), actor: 'He thong' }),
    ],
  },
  {
    id: 9,
    code: generateRequestCode(115),
    status: REQUEST_STATUS.APPOINTMENT_CREATED,
    name: 'Nguyen Hoang Long',
    phone: '0990123456',
    email: 'long.nguyen@gmail.com',
    service_ids: ['extraction'],
    branch_id: 'q3',
    preferred_date: isoDate(-2),
    preferred_time_slot_id: '08-09',
    customer_note: 'Nho rang khon hai ben.',
    internal_note: '',
    patient_id: 3,
    appointment_id: 2,
    appointment_code: generateAppointmentCode(2),
    appointment_status: APPOINTMENT_STATUS.WAITING_DOCTOR_ASSIGNMENT,
    email_status: EMAIL_STATUS.FAILED,
    processed_by: 'le_tan',
    processed_at: isoOffset(-80),
    source: 'landing_page',
    submitted_at: isoOffset(-100),
    device: 'iPhone · Safari',
    ip: '113.161.10.10',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-100), actor: 'He thong' }),
      buildHistoryEntry('processing_started', { at: isoOffset(-81), actor: 'le_tan' }),
      buildHistoryEntry('patient_linked', { at: isoOffset(-80), actor: 'le_tan' }),
      buildHistoryEntry('appointment_created', { at: isoOffset(-80), actor: 'le_tan', note: 'Tao lich hen ' + generateAppointmentCode(2) }),
      buildHistoryEntry('email_failed', { at: isoOffset(-80), actor: 'He thong', note: 'Email server tra ve loi 5.5.0 - mailbox unavailable' }),
    ],
  },
  {
    id: 10,
    code: generateRequestCode(114),
    status: REQUEST_STATUS.PENDING,
    name: 'Mai Quoc Bao',
    phone: '0901111222',
    email: 'bao.mai@gmail.com',
    service_ids: ['scaling', 'whitening'],
    branch_id: 'q7',
    preferred_date: isoDate(4),
    preferred_time_slot_id: '13-14',
    customer_note: 'Lam dich vu ket hop neu duoc.',
    internal_note: '',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: null,
    processed_at: null,
    source: 'landing_page',
    submitted_at: isoOffset(-40),
    device: 'Windows · Chrome',
    ip: '113.160.40.40',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-40), actor: 'He thong' }),
    ],
  },
  {
    id: 11,
    code: generateRequestCode(113),
    status: REQUEST_STATUS.APPOINTMENT_CREATED,
    name: 'Tran Thi Bich',
    phone: '0908889999',
    email: 'bich.tran@gmail.com',
    service_ids: ['porcelain'],
    branch_id: 'q1',
    preferred_date: isoDate(-5),
    preferred_time_slot_id: '14-15',
    customer_note: 'Lam rang su 4 cai cua.',
    internal_note: '',
    patient_id: 1,
    appointment_id: 3,
    appointment_code: generateAppointmentCode(3),
    appointment_status: APPOINTMENT_STATUS.WAITING_DOCTOR_ASSIGNMENT,
    email_status: EMAIL_STATUS.SENT,
    processed_by: 'le_tan',
    processed_at: isoOffset(-150),
    source: 'landing_page',
    submitted_at: isoOffset(-200),
    device: 'macOS · Safari',
    ip: '171.244.5.5',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-200), actor: 'He thong' }),
      buildHistoryEntry('appointment_created', { at: isoOffset(-150), actor: 'le_tan', note: 'Tao lich hen ' + generateAppointmentCode(3) }),
    ],
  },
  {
    id: 12,
    code: generateRequestCode(112),
    status: REQUEST_STATUS.PENDING,
    name: 'Nguyen Thi Mai',
    phone: '0907778888',
    email: 'mai.nguyen.thi@gmail.com',
    service_ids: ['braces'],
    branch_id: 'q1',
    preferred_date: isoDate(5),
    preferred_time_slot_id: '15-16',
    customer_note: 'Nho rang khon truoc khi nieng.',
    internal_note: '',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: null,
    processed_at: null,
    source: 'landing_page',
    submitted_at: isoOffset(-3),
    device: 'Android · Chrome Mobile',
    ip: '113.160.60.60',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-3), actor: 'He thong' }),
    ],
  },
  {
    id: 13,
    code: generateRequestCode(111),
    status: REQUEST_STATUS.PROCESSING,
    name: 'Phan Van Hung',
    phone: '0906667777',
    email: 'hung.phan@gmail.com',
    service_ids: ['extraction'],
    branch_id: 'q7',
    preferred_date: isoDate(1),
    preferred_time_slot_id: '17-1730',
    customer_note: 'Nho gap, dang dau nhuc.',
    internal_note: 'Da goi xac nhan, doi khach phan hoi gio.',
    patient_id: null,
    appointment_id: null,
    appointment_code: null,
    email_status: EMAIL_STATUS.NONE,
    processed_by: 'le_tan',
    processed_at: isoOffset(-2),
    source: 'landing_page',
    submitted_at: isoOffset(-10),
    device: 'Windows · Chrome',
    ip: '113.161.20.20',
    proposed_slots: [],
    reject_reason: null,
    history: [
      buildHistoryEntry('request_created', { at: isoOffset(-10), actor: 'He thong' }),
      buildHistoryEntry('processing_started', { at: isoOffset(-2), actor: 'le_tan' }),
    ],
  },
];

// Counter to continue sequence sau seed.
export const NEXT_REQUEST_SEQ = 124;
export const NEXT_APPOINTMENT_SEQ = 4;
export const NEXT_PATIENT_SEQ = 9999;
